### PR TITLE
Make VNC work with Python 3.9

### PR DESCRIPTION
**Pull request by jonico**
* update WEBSOCKETIFY to version 0.10.0 to make it work with Python 3.9
* version 0.9.0 resulted in error "handler exception: 'array.array' object has no attribute 'fromstring'
* upstream fix: https://github.com/novnc/websockify/issues/473

### CODE REVIEW

**Comment by Chuxel** [comment]
Good catch!  Thanks.
